name: wick
base: core24
version: git
summary: WAMP in Command-line
description: |
  WAMP in Command-line

grade: stable
confinement: strict
compression: lzo

parts:
  wick:
    plugin: rust
    source: .
    build-packages:
      - pkg-config
      - libssl-dev

apps:
  wick:
    command: bin/wick
    plugs:
      - network
      - network-bind
      - home
